/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:6dfe964c-047a-435f-b44c-caf2ff57d821',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_QrqIRi0IC',
  aws_user_pools_web_client_id: '28170cvv6ous1ttpig6b0f7csn',
  oauth: {
    domain: 'kleeencloud-develop.auth.us-east-1.amazoncognito.com',
    scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'http://localhost:4200/,https://develop.kleeen.cloud/',
    redirectSignOut: 'http://localhost:4200/,https://develop.kleeen.cloud/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
};


export default awsmobile;
